apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: hello-lb
            servicePort: 9999
