apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - image: asia.gcr.io/$PROJECT_ID/hello
      imagePullPolicy: Always
      name: hello
      env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: hello-config
              key: msg


